//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMMOBILISATION.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAMILLES_IMMOBILISATIONS
    {
        public FAMILLES_IMMOBILISATIONS()
        {
            this.IMMOBILISATIONS = new HashSet<IMMOBILISATIONS>();
        }
    
        public int ID { get; set; }
        public string FAMILLE { get; set; }
        public string TYPE { get; set; }
        public string INTITULE { get; set; }
        public Nullable<int> NATURE { get; set; }
    
        public virtual NATURES_BIENS NATURES_BIENS { get; set; }
        public virtual ICollection<IMMOBILISATIONS> IMMOBILISATIONS { get; set; }
    }
}
