//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMMOBILISATION.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FICHES_TECHNIQUES
    {
        public int ID { get; set; }
        public string MARQUE { get; set; }
        public byte[] PHOTO { get; set; }
        public string DESCRIPTION { get; set; }
        public string COMPOSITION { get; set; }
        public string LIEU_FABRICATION { get; set; }
        public string DIMENSION { get; set; }
        public string COULEUR { get; set; }
        public string POID { get; set; }
        public string PUISSANCE { get; set; }
        public string CONSOMMATION { get; set; }
        public Nullable<int> IMMOBILISATION { get; set; }
    
        public virtual IMMOBILISATIONS IMMOBILISATIONS { get; set; }
    }
}
