//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMMOBILISATION.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class IMMOBILISATIONS
    {
        public IMMOBILISATIONS()
        {
            this.FICHES_TECHNIQUES = new HashSet<FICHES_TECHNIQUES>();
        }
        private DateTime _date = DateTime.Today;
        private Boolean _boolean = true;

        public int ID { get; set; }
        public string TYPE { get; set; }
        public string CODE { get; set; }
        public string DESIGNATION { get; set; }
        [DefaultValue(0)]
        public double VALEUR_ACQUISITION_TTC { get; set; }
        public System.DateTime DATE_AQUISITION
        {
            get { return _date; }
            set { _date = value; }
        }
        public System.DateTime DATE_MISE_EN_SERVICE
        {
            get { return _date; }
            set { _date = value; }
        }

        public Nullable<int> FOURNISSEUR { get; set; }
        public Nullable<int> FAMILLE { get; set; }
        public string CODE_A_BARRE { get; set; }
        public bool DISPONIBILITE
        {
            get { return _boolean; }
            set { _boolean = value; }
        }

        public virtual ICollection<FICHES_TECHNIQUES> FICHES_TECHNIQUES { get; set; }
        [ForeignKey("FAMILLE")]
        public virtual FAMILLES_IMMOBILISATIONS FAMILLES_IMMOBILISATIONS { get; set; }
        [ForeignKey("FOURNISSEUR")]
        public virtual TIERS TIERS { get; set; }
    }
}
