//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMMOBILISATION.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMMOBILISATIONS
    {
        public IMMOBILISATIONS()
        {
            this.FICHES_TECHNIQUES = new HashSet<FICHES_TECHNIQUES>();
        }
    
        public int ID { get; set; }
    
        public virtual ICollection<FICHES_TECHNIQUES> FICHES_TECHNIQUES { get; set; }
    }
}
