//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMMOBILISATION.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIERS
    {
        public int ID { get; set; }
        public string TYPE { get; set; }
        public string INTITULE { get; set; }
        public string ABREGE { get; set; }
        public string QUALITE { get; set; }
        public string INTERLOCUTEUR { get; set; }
        public string COMMENTAIRE { get; set; }
    }
}
